site_name: Cobalt Pipelines

theme:
  name: material
  icon:
    logo: material/library
  palette:
    primary: 'indigo'
    accent: 'deep orange'
  font:
    text: 'Ubuntu'
    code: 'Ubuntu Mono'
repo_name: 'pipeline-library'
repo_url:  https://github.com/hariharPai/MyWebPages
extra:
  social:
    - icon: fontawesome/brands/slack
      type: 'slack'
      link: 'https://sap-ariba.slack.com/archives/C96L4NTTK'
plugins:
    - search
markdown_extensions:
  - codehilite
  - admonition
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format
extra_css:
  - https://unpkg.com/mermaid@7.1.2/dist/mermaid.css
extra_javascript:
  - https://unpkg.com/mermaid@7.1.2/dist/mermaid.min.js
